apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: zf30w1mwv-nodejs
  janus-idp.io/tekton: zf30w1mwv-nodejs
  backstage.io/kubernetes-id: zf30w1mwv-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zf30w1mwv-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
